// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIDrVJ2eBMgS1uLn5zRY1nZNJgvV0683g',
    appId: '1:540926420878:web:4886eb74ca96a5df9b26df',
    messagingSenderId: '540926420878',
    projectId: 'scmu-terrariums',
    authDomain: 'scmu-terrariums.firebaseapp.com',
    databaseURL: 'https://scmu-terrariums-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scmu-terrariums.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnEA4DJnNbj9fXh-pI2hE_Eixtx-6akYE',
    appId: '1:540926420878:android:b66448c693ce9ead9b26df',
    messagingSenderId: '540926420878',
    projectId: 'scmu-terrariums',
    databaseURL: 'https://scmu-terrariums-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scmu-terrariums.appspot.com',
  );

}